---
title: ConquerOS - Homepage
author: HeroBuxx
email: me@herobuxx.xyz
description: Simple yet Powerful CAF Based ROM.
baseurl: "/"
url: ''
defaults:
- scope:
    path: ''
  values:
    layout: default
plugins:
- jekyll-feed
- jekyll-menus
