---
title: ConquerOS - Homepage
author: HeroBuxx
email: me@herobuxx.xyz
description: ConquerOS is a smiple CAF Based Custom ROM
baseurl: ''
url: ''
defaults:
- scope:
    path: ''
  values:
    layout: default
plugins:
- jekyll-feed
- jekyll-menus
